apiVersion: v1    # Указывает версию API для этого ресурса, "v1" — основная версия для Service.
kind: Service     # Определяет тип ресурса, здесь это Service для обеспечения сетевого доступа к подам.
metadata:         # Метаданные содержат информацию о самом Service.
  name: app-service        # Имя Service, используется для обращения к нему в кластере.
  namespace: app-namespace # Указывает, что Service создается в namespace "app-namespace".
spec:                     # Спецификация определяет желаемое состояние Service.
  type: ClusterIP         # Устанавливает тип Service как ClusterIP, доступен только внутри кластера (по умолчанию).
  ports:                  # Определяет порты, которые Service открывает, и как они связаны с подами.
    - name: app-listener  # Имя порта для удобства, полезно при нескольких портах.
      protocol: TCP       # Указывает протокол для порта, TCP — стандарт для веб-трафика.
      port: 3000          # Порт (3000), на котором Service слушает внутри кластера.
      targetPort: 8080    # Порт на целевых подах (8080), куда перенаправляется трафик, соответствует containerPort.
  selector:               # Выбирает поды, к которым Service направляет трафик, по меткам.
    app: main             # Соответствует подам с меткой "app: main", связывает Service с подами Deployment.