apiVersion: apps/v1   # Определяет API-версию, используемую для создания Deployment
kind: Deployment      # Указывает, что создается объект типа Deployment
metadata:             # Метаданные для Deployment
  name: app-deployment      # Имя объекта Deployment
  namespace: app-namespace  # Указывает, что Deployment создается в namespace "app-namespace".
  labels:           # Метки, которые можно использовать для группировки и фильтрации ресурсов (метки для объекта Deployment).
    env: prod       # Метка окружения, указывает, что это продакшн
    app: main       # Метка, идентифицирующая приложение
spec:               # Основная спецификация Deployment
  replicas: 4       # Количество реплик (подов), которые должны быть запущены
  selector:         # Указывает, какие поды принадлежат этому Deployment
    matchLabels:    # Определяет соответствие меткам
      app: main     # Ищет поды с меткой "app: main"
  template:         # Шаблон для создаваемых подов
    metadata:       # Метаданные для подов
      labels:       # Метки, которые будут назначены подам
        app: main   # Метка для идентификации подов
    spec:           # Спецификация подов
      containers:   # Определяет список контейнеров внутри пода
        - name: my-go-app           # Имя контейнера в поде
          image: petrovevgeny/my-go-app:v1.0.0   # Docker-образ, который будет использоваться в контейнере
          ports:                    # Определяет список портов, которые контейнер будет слушать
            - containerPort: 8080   # Открывает порт 8080 внутри контейнера для входящих подключений
          resources:                # Определяет ограничения ресурсов для контейнера
            limits:                 # Определяет максимальное количество ресурсов, которое контейнер может использовать.
              cpu: 200m             # Максимальное количество процессорного времени, которое может использовать контейнер (200 милли-CPU, что соответствует 0.2 CPU)
              memory: 128Mi         # Максимальное количество памяти, которое может использовать контейнер (128 мегабайт)
            requests:               # Определяет минимальные ресурсы, которые гарантированно получит контейнер
              cpu: 100m             # Минимальное количество процессорного времени, которое гарантированно будет выделено контейнеру (100 милли-CPU, что соответствует 0.2 CPU)
              memory: 64Mi          # Минимальное количество оперативной памяти, которое гарантированно будет выделено контейнеру (64 мегабайт)