apiVersion: networking.k8s.io/v1  # Указывает версию API для этого ресурса.
kind: Ingress                     # Определяет тип ресурса, здесь это Ingress для управления внешним доступом к Service.
metadata:                         # Метаданные содержат информацию о самом Ingress.
  name: my-ingress                # Имя Ingress.
  annotations:                    # Аннотации добавляют дополнительную конфигурацию для контроллера Ingress (например, NGINX).
    nginx.ingress.kubernetes.io/add-base-url: "true" # Добавляет базовый URL к ответам, полезно для переписывания URL в NGINX.
spec:                             # Спецификация определяет желаемое состояние Ingress.
  ingressClassName: nginx         # Указывает класс Ingress (nginx), связывает его с контроллером NGINX.
  rules:                          # Определяет правила маршрутизации входящего трафика.
    - host: app.lan               # Указывает хост (домен), к которому применяется это правило (app.lan).
      http:                       # Определяет правила маршрутизации для HTTP-трафика.
        paths:                    # Список путей для маршрутизации трафика этого хоста.
          - pathType: Prefix      # Указывает, что путь — это префикс, то есть включает "/" и подпуть (например, "/about").
            path: "/"             # Определяет путь (корень), для которого применяется правило.
            backend:              # Указывает бэкенд (Service), куда направляется трафик.
              service:            # Ссылка на Service, определенный ранее.
                name: my-service  # Имя Service ("my-service"), к которому идет трафик.
                port:             # Указывает порт Service, на который направляется трафик.
                  number: 3000    # Номер порта (3000), соответствующий порту Service.