apiVersion: v1                  # Версия API для Secret.
kind: Secret                    # Тип ресурса — Secret для хранения конфиденциальных данных.
metadata:                       # Метаданные секрета.
  name: postgres-secret         # Имя секрета, используется в Deployment.
  namespace: app-namespace      # Указывает, что Secret создается в namespace "app-namespace".
type: Opaque                    # Тип секрета — непрозрачный, для произвольных данных.
data:                           # Данные секрета в закодированном виде (base64).
  POSTGRES_DB: ZGVtbw==         # Имя базы данных ('demo' в base64).
  POSTGRES_USER: ZGVtbw==       # Имя пользователя ('demo' в base64).
  POSTGRES_PASSWORD: ZGVtbw==   # Пароль ('demo' в base64).