apiVersion: v1              # Версия API для ресурса Service.
kind: Service               # Тип ресурса — Service для обеспечения доступа к подам.
metadata:                   # Метаданные сервиса.
  name: postgres-clusterip  # Имя сервиса, используется для обращения внутри кластера.
  namespace: app-namespace  # Указывает, что Service создается в namespace "app-namespace".
spec:                       # Спецификация сервиса.
  type: ClusterIP           # Тип сервиса — ClusterIP, доступен только внутри кластера.
  ports:                    # Порты, которые сервис открывает.
    - port: 5432            # Порт 5432 для подключения к PostgreSQL.
      protocol: TCP         # Протокол передачи данных — TCP.
  selector:                 # Метки для выбора подов, к которым привязан сервис.
    components: postgres    # Соответствует подам с меткой 'components: postgres'.