apiVersion: v1
kind: Pod
metadata:
  name: my-pod-php-app
  labels:
    env: prod
    app: main
    owner: Evgeny
spec:
  containers:
    - name: my-php-app
      image: c0nsci0usness/my-php-app:latest
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128M"
          cpu: "500m"