apiVersion: v1          # Версия API, используемая для создания объекта
kind: Pod               # Тип объекта, который мы создаем (Pod)
metadata:               # Метаданные для объекта
  name: my-pod-php-app  # Имя Pod
  labels:               # Метки для идентификации Pod
    env: prod           # Метка для обозначения окружения (продакшен)
    app: main           # Метка для обозначения приложения

spec:                       # Спецификация Pod
  containers:               # Список контейнеров, которые будут запущены в Pod
    - name: my-php-app      # Имя контейнера
      image: c0nsci0usness/my-php-app-v1:latest  # Образ контейнера, который будет использоваться
      ports:                # Порты, которые контейнер будет слушать
        - containerPort: 80 # Порт контейнера, который будет использоваться приложением
      resources:            # Ресурсы, которые контейнер может использовать
        limits:             # Ограничения ресурсов для контейнера
          memory: "128M"    # Максимальное количество памяти, которое может использовать контейнер (128 мегабайт)
          cpu: "500m"       # Максимальное количество процессорного времени, которое может использовать контейнер (500 милли-CPU, что соответствует 0.5 CPU)

---
apiVersion: v1                  # Версия API для Service
kind: Service                   # Тип объекта, который мы создаем (Service)
metadata:                       # Метаданные для объекта Service
  name: my-single-pod-service   # Имя Service

spec:                     # Спецификация Service
  type: NodePort          # Тип сервиса (NodePort позволяет доступ к сервису через любой узел кластера)
  ports:                  # Порты, которые сервис будет использовать
    - name: app-listener  # Имя порта для удобства
      protocol: TCP       # Протокол, используемый сервисом (TCP)
      port: 3000          # Порт, на котором сервис будет доступен. Порт сервиса внутри кластера.
      targetPort: 80      # Порт, на который сервис будет перенаправлять трафик (порт контейнера) с 3000 на 80. Порт контейнера внутри пода.
      nodePort: 31200     # Порт, который будет использоваться для доступа к сервису на узлах кластера из вне. Цепочка запроса: 31200 - 3000 - 80
  selector:               # Селектор для определения, к каким Pod будет направляться трафик
    app: main             # Метка, которая должна совпадать с метками в Pod (в данном случае, с меткой app: main)
